# enable_rgb = true

[env]
TERM = "xterm-256color"

[font]
size = 8

[font.normal]
family = "Cascadia Code"
style = "Regular"

[[keyboard.bindings]]
chars = ""
key = "F13"
mods = "None"

[window]
opacity = 0.5

[window.padding]
x = 0
y = 0
